# Generated by Django 4.2.23 on 2025-07-24 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_employee_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='position_code',
            field=models.CharField(default=11111, max_length=10),
            preserve_default=False,
        ),
    ]
