# Generated by Django 4.2.23 on 2025-07-25 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_employee_employee_code_employee_position_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='position_code',
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_code',
            field=models.CharField(default='UNKNOWN', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
